# Travis configuration

language: objective-c
notifications:
  email: false
script:
  - xctool build -project WKTParser.xcodeproj -scheme WKTParser -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xctool test -project WKTParser.xcodeproj -scheme WKTParserTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
 
